# Cloud Build configuration for frontend CI/CD
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=https://cgs-multiagent-777957407803.us-central1.run.app'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cgsai-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cgsai-frontend:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cgsai-frontend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cgsai-frontend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cgsai-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cgsai-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'

images:
  - 'gcr.io/$PROJECT_ID/cgsai-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/cgsai-frontend:latest'

options:
  machineType: 'E2_MEDIUM'
  logging: CLOUD_LOGGING_ONLY

timeout: '600s'
