# Cloud Build configuration for frontend - Build only
# Deployment is handled separately by deploy.sh
steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "VITE_API_URL=${_VITE_API_URL}"
      - "-t"
      - "gcr.io/$PROJECT_ID/cgsai-frontend:latest"
      - "."

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/cgsai-frontend:latest"

images:
  - "gcr.io/$PROJECT_ID/cgsai-frontend:latest"

options:
  machineType: "E2_MEDIUM"
  logging: CLOUD_LOGGING_ONLY

timeout: "600s"

# Substitutions (can be overridden by: gcloud builds submit --substitutions)
substitutions:
  _VITE_API_URL: "http://localhost:8000/api/v1"
